name: Build

on: [push, pull_request]

jobs:
  build_dart_packages:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        package: ["timeago"]
        sdk: ["dev"]

    steps:
      - uses: actions/checkout@v2

      - uses: dart-lang/setup-dart@v0.1
        with:
          channel: ${{ matrix.sdk }}

      - name: Install dependencies
        working-directory: ${{ matrix.package }}
        run: pub get

      - name: Analyze
        working-directory: ${{ matrix.package }}
        run: dartanalyzer --fatal-infos --fatal-warnings .

      - name: Run tests
        working-directory: ${{ matrix.package }}
        run: pub run test
